{
url: 'https://integrasus.saude.ce.gov.br/api/coronavirus/curva-epidemiologica?dataInicio=2020-01-01&dataFim=2023-07-12&minDate=2020-01-01&maxDate=2023-07-12&tipo=Confirmados&idMunicipio=&idRegiaoSaude=&idMacrorregiao=&casosHospitalizados=false&casosProfissionais=false&casosIndigenas=false&casosEstudante=false',
url_vacina: 'http://10.17.1.111:8050/get_qtd_vacinados/todos/',
url_vacina_historico: 'http://10.17.1.111:8050/get_historico_vacinados/'}